-- Phase B: Investment Flow Schema Migration
-- Creates offering-based investment tables

-- 1. Offering Investments Table
CREATE TABLE IF NOT EXISTS `offering_investments` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `userId` INT NOT NULL,
  `offeringId` INT NOT NULL,
  `propertyId` INT NOT NULL,
  `numberOfShares` INT NOT NULL,
  `pricePerShare` INT NOT NULL,
  `investmentAmount` INT NOT NULL,
  `platformFeePercentage` INT DEFAULT 0,
  `platformFeeAmount` INT DEFAULT 0,
  `processingFeeAmount` INT DEFAULT 0,
  `totalAmount` INT NOT NULL,
  `ownershipPercentage` INT NOT NULL,
  `status` ENUM('reserved', 'pending_payment', 'payment_processing', 'payment_failed', 'completed', 'cancelled', 'refunded') NOT NULL DEFAULT 'reserved',
  `reservedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reservationExpiresAt` TIMESTAMP NOT NULL,
  `paymentMethod` ENUM('bank_transfer', 'credit_card', 'debit_card', 'wallet', 'wire_transfer', 'check'),
  `paymentStatus` ENUM('pending', 'processing', 'completed', 'failed', 'refunded') DEFAULT 'pending',
  `paymentReference` VARCHAR(255),
  `paymentProofUrl` TEXT,
  `paymentProofKey` TEXT,
  `paidAt` TIMESTAMP NULL,
  `isAccreditedInvestor` BOOLEAN NOT NULL DEFAULT FALSE,
  `accreditationVerifiedAt` TIMESTAMP NULL,
  `accreditationDocumentUrl` TEXT,
  `agreementAcceptedAt` TIMESTAMP NULL,
  `agreementIpAddress` VARCHAR(45),
  `agreementUserAgent` TEXT,
  `certificateIssued` BOOLEAN DEFAULT FALSE,
  `certificateIssuedAt` TIMESTAMP NULL,
  `certificateNumber` VARCHAR(100),
  `certificateUrl` TEXT,
  `completedAt` TIMESTAMP NULL,
  `distributionFrequency` ENUM('monthly', 'quarterly', 'semi_annual', 'annual'),
  `firstDistributionDate` TIMESTAMP NULL,
  `exitedAt` TIMESTAMP NULL,
  `exitReason` TEXT,
  `exitAmount` INT,
  `ipAddress` VARCHAR(45),
  `userAgent` TEXT,
  `notes` TEXT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`userId`) REFERENCES `users`(`id`),
  FOREIGN KEY (`offeringId`) REFERENCES `offerings`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`propertyId`) REFERENCES `properties`(`id`),
  INDEX `offering_investments_user_id_idx` (`userId`),
  INDEX `offering_investments_offering_id_idx` (`offeringId`),
  INDEX `offering_investments_property_id_idx` (`propertyId`),
  INDEX `offering_investments_status_idx` (`status`),
  INDEX `offering_investments_payment_status_idx` (`paymentStatus`),
  INDEX `offering_investments_reservation_expires_idx` (`reservationExpiresAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Offering Investment Documents Table
CREATE TABLE IF NOT EXISTS `offering_investment_documents` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `investmentId` INT NOT NULL,
  `documentType` ENUM('subscription_agreement', 'operating_agreement', 'accreditation_verification', 'payment_proof', 'share_certificate', 'tax_document', 'other') NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `fileUrl` TEXT NOT NULL,
  `fileKey` TEXT NOT NULL,
  `fileName` VARCHAR(255) NOT NULL,
  `mimeType` VARCHAR(100),
  `fileSize` INT,
  `uploadedBy` INT,
  `uploadedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `signedAt` TIMESTAMP NULL,
  `signatureData` TEXT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`investmentId`) REFERENCES `offering_investments`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`uploadedBy`) REFERENCES `users`(`id`),
  INDEX `offering_investment_docs_investment_id_idx` (`investmentId`),
  INDEX `offering_investment_docs_type_idx` (`documentType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Offering Distributions Table
CREATE TABLE IF NOT EXISTS `offering_distributions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `investmentId` INT NOT NULL,
  `offeringId` INT NOT NULL,
  `userId` INT NOT NULL,
  `distributionType` ENUM('rental_income', 'capital_gain', 'dividend', 'interest', 'other') NOT NULL,
  `distributionPeriod` VARCHAR(50),
  `distributionDate` TIMESTAMP NOT NULL,
  `grossAmount` INT NOT NULL,
  `taxWithheld` INT DEFAULT 0,
  `feesDeducted` INT DEFAULT 0,
  `netAmount` INT NOT NULL,
  `paymentMethod` VARCHAR(50),
  `paymentReference` VARCHAR(255),
  `paymentStatus` ENUM('pending', 'processing', 'completed', 'failed') NOT NULL DEFAULT 'pending',
  `paidAt` TIMESTAMP NULL,
  `notes` TEXT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`investmentId`) REFERENCES `offering_investments`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`offeringId`) REFERENCES `offerings`(`id`),
  FOREIGN KEY (`userId`) REFERENCES `users`(`id`),
  INDEX `offering_distributions_investment_id_idx` (`investmentId`),
  INDEX `offering_distributions_offering_id_idx` (`offeringId`),
  INDEX `offering_distributions_user_id_idx` (`userId`),
  INDEX `offering_distributions_date_idx` (`distributionDate`),
  INDEX `offering_distributions_payment_status_idx` (`paymentStatus`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Offering Investment History Table
CREATE TABLE IF NOT EXISTS `offering_investment_history` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `investmentId` INT NOT NULL,
  `previousStatus` VARCHAR(50),
  `newStatus` VARCHAR(50) NOT NULL,
  `changeReason` TEXT,
  `changeNotes` TEXT,
  `changedBy` INT,
  `changedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ipAddress` VARCHAR(45),
  `userAgent` TEXT,
  FOREIGN KEY (`investmentId`) REFERENCES `offering_investments`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`changedBy`) REFERENCES `users`(`id`),
  INDEX `offering_investment_history_investment_id_idx` (`investmentId`),
  INDEX `offering_investment_history_changed_at_idx` (`changedAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
