/**
 * Comprehensive list of countries with English and Arabic names
 * ISO 3166-1 alpha-2 country codes
 */

export interface Country {
  code: string;
  nameEn: string;
  nameAr: string;
  flag: string; // Unicode flag emoji
}

export const countries: Country[] = [
  { code: "AF", nameEn: "Afghanistan", nameAr: "أفغانستان", flag: "🇦🇫" },
  { code: "AL", nameEn: "Albania", nameAr: "ألبانيا", flag: "🇦🇱" },
  { code: "DZ", nameEn: "Algeria", nameAr: "الجزائر", flag: "🇩🇿" },
  { code: "AD", nameEn: "Andorra", nameAr: "أندورا", flag: "🇦🇩" },
  { code: "AO", nameEn: "Angola", nameAr: "أنغولا", flag: "🇦🇴" },
  { code: "AR", nameEn: "Argentina", nameAr: "الأرجنتين", flag: "🇦🇷" },
  { code: "AM", nameEn: "Armenia", nameAr: "أرمينيا", flag: "🇦🇲" },
  { code: "AU", nameEn: "Australia", nameAr: "أستراليا", flag: "🇦🇺" },
  { code: "AT", nameEn: "Austria", nameAr: "النمسا", flag: "🇦🇹" },
  { code: "AZ", nameEn: "Azerbaijan", nameAr: "أذربيجان", flag: "🇦🇿" },
  { code: "BH", nameEn: "Bahrain", nameAr: "البحرين", flag: "🇧🇭" },
  { code: "BD", nameEn: "Bangladesh", nameAr: "بنغلاديش", flag: "🇧🇩" },
  { code: "BY", nameEn: "Belarus", nameAr: "بيلاروسيا", flag: "🇧🇾" },
  { code: "BE", nameEn: "Belgium", nameAr: "بلجيكا", flag: "🇧🇪" },
  { code: "BZ", nameEn: "Belize", nameAr: "بليز", flag: "🇧🇿" },
  { code: "BJ", nameEn: "Benin", nameAr: "بنين", flag: "🇧🇯" },
  { code: "BT", nameEn: "Bhutan", nameAr: "بوتان", flag: "🇧🇹" },
  { code: "BO", nameEn: "Bolivia", nameAr: "بوليفيا", flag: "🇧🇴" },
  { code: "BA", nameEn: "Bosnia and Herzegovina", nameAr: "البوسنة والهرسك", flag: "🇧🇦" },
  { code: "BW", nameEn: "Botswana", nameAr: "بوتسوانا", flag: "🇧🇼" },
  { code: "BR", nameEn: "Brazil", nameAr: "البرازيل", flag: "🇧🇷" },
  { code: "BN", nameEn: "Brunei", nameAr: "بروناي", flag: "🇧🇳" },
  { code: "BG", nameEn: "Bulgaria", nameAr: "بلغاريا", flag: "🇧🇬" },
  { code: "BF", nameEn: "Burkina Faso", nameAr: "بوركينا فاسو", flag: "🇧🇫" },
  { code: "BI", nameEn: "Burundi", nameAr: "بوروندي", flag: "🇧🇮" },
  { code: "KH", nameEn: "Cambodia", nameAr: "كمبوديا", flag: "🇰🇭" },
  { code: "CM", nameEn: "Cameroon", nameAr: "الكاميرون", flag: "🇨🇲" },
  { code: "CA", nameEn: "Canada", nameAr: "كندا", flag: "🇨🇦" },
  { code: "CV", nameEn: "Cape Verde", nameAr: "الرأس الأخضر", flag: "🇨🇻" },
  { code: "CF", nameEn: "Central African Republic", nameAr: "جمهورية أفريقيا الوسطى", flag: "🇨🇫" },
  { code: "TD", nameEn: "Chad", nameAr: "تشاد", flag: "🇹🇩" },
  { code: "CL", nameEn: "Chile", nameAr: "تشيلي", flag: "🇨🇱" },
  { code: "CN", nameEn: "China", nameAr: "الصين", flag: "🇨🇳" },
  { code: "CO", nameEn: "Colombia", nameAr: "كولومبيا", flag: "🇨🇴" },
  { code: "KM", nameEn: "Comoros", nameAr: "جزر القمر", flag: "🇰🇲" },
  { code: "CG", nameEn: "Congo", nameAr: "الكونغو", flag: "🇨🇬" },
  { code: "CR", nameEn: "Costa Rica", nameAr: "كوستاريكا", flag: "🇨🇷" },
  { code: "HR", nameEn: "Croatia", nameAr: "كرواتيا", flag: "🇭🇷" },
  { code: "CU", nameEn: "Cuba", nameAr: "كوبا", flag: "🇨🇺" },
  { code: "CY", nameEn: "Cyprus", nameAr: "قبرص", flag: "🇨🇾" },
  { code: "CZ", nameEn: "Czech Republic", nameAr: "التشيك", flag: "🇨🇿" },
  { code: "DK", nameEn: "Denmark", nameAr: "الدنمارك", flag: "🇩🇰" },
  { code: "DJ", nameEn: "Djibouti", nameAr: "جيبوتي", flag: "🇩🇯" },
  { code: "DO", nameEn: "Dominican Republic", nameAr: "جمهورية الدومينيكان", flag: "🇩🇴" },
  { code: "EC", nameEn: "Ecuador", nameAr: "الإكوادور", flag: "🇪🇨" },
  { code: "EG", nameEn: "Egypt", nameAr: "مصر", flag: "🇪🇬" },
  { code: "SV", nameEn: "El Salvador", nameAr: "السلفادور", flag: "🇸🇻" },
  { code: "GQ", nameEn: "Equatorial Guinea", nameAr: "غينيا الاستوائية", flag: "🇬🇶" },
  { code: "ER", nameEn: "Eritrea", nameAr: "إريتريا", flag: "🇪🇷" },
  { code: "EE", nameEn: "Estonia", nameAr: "إستونيا", flag: "🇪🇪" },
  { code: "ET", nameEn: "Ethiopia", nameAr: "إثيوبيا", flag: "🇪🇹" },
  { code: "FJ", nameEn: "Fiji", nameAr: "فيجي", flag: "🇫🇯" },
  { code: "FI", nameEn: "Finland", nameAr: "فنلندا", flag: "🇫🇮" },
  { code: "FR", nameEn: "France", nameAr: "فرنسا", flag: "🇫🇷" },
  { code: "GA", nameEn: "Gabon", nameAr: "الغابون", flag: "🇬🇦" },
  { code: "GM", nameEn: "Gambia", nameAr: "غامبيا", flag: "🇬🇲" },
  { code: "GE", nameEn: "Georgia", nameAr: "جورجيا", flag: "🇬🇪" },
  { code: "DE", nameEn: "Germany", nameAr: "ألمانيا", flag: "🇩🇪" },
  { code: "GH", nameEn: "Ghana", nameAr: "غانا", flag: "🇬🇭" },
  { code: "GR", nameEn: "Greece", nameAr: "اليونان", flag: "🇬🇷" },
  { code: "GT", nameEn: "Guatemala", nameAr: "غواتيمالا", flag: "🇬🇹" },
  { code: "GN", nameEn: "Guinea", nameAr: "غينيا", flag: "🇬🇳" },
  { code: "GW", nameEn: "Guinea-Bissau", nameAr: "غينيا بيساو", flag: "🇬🇼" },
  { code: "GY", nameEn: "Guyana", nameAr: "غيانا", flag: "🇬🇾" },
  { code: "HT", nameEn: "Haiti", nameAr: "هايتي", flag: "🇭🇹" },
  { code: "HN", nameEn: "Honduras", nameAr: "هندوراس", flag: "🇭🇳" },
  { code: "HU", nameEn: "Hungary", nameAr: "المجر", flag: "🇭🇺" },
  { code: "IS", nameEn: "Iceland", nameAr: "آيسلندا", flag: "🇮🇸" },
  { code: "IN", nameEn: "India", nameAr: "الهند", flag: "🇮🇳" },
  { code: "ID", nameEn: "Indonesia", nameAr: "إندونيسيا", flag: "🇮🇩" },
  { code: "IR", nameEn: "Iran", nameAr: "إيران", flag: "🇮🇷" },
  { code: "IQ", nameEn: "Iraq", nameAr: "العراق", flag: "🇮🇶" },
  { code: "IE", nameEn: "Ireland", nameAr: "أيرلندا", flag: "🇮🇪" },
  { code: "IL", nameEn: "Israel", nameAr: "إسرائيل", flag: "🇮🇱" },
  { code: "IT", nameEn: "Italy", nameAr: "إيطاليا", flag: "🇮🇹" },
  { code: "JM", nameEn: "Jamaica", nameAr: "جامايكا", flag: "🇯🇲" },
  { code: "JP", nameEn: "Japan", nameAr: "اليابان", flag: "🇯🇵" },
  { code: "JO", nameEn: "Jordan", nameAr: "الأردن", flag: "🇯🇴" },
  { code: "KZ", nameEn: "Kazakhstan", nameAr: "كازاخستان", flag: "🇰🇿" },
  { code: "KE", nameEn: "Kenya", nameAr: "كينيا", flag: "🇰🇪" },
  { code: "KW", nameEn: "Kuwait", nameAr: "الكويت", flag: "🇰🇼" },
  { code: "KG", nameEn: "Kyrgyzstan", nameAr: "قيرغيزستان", flag: "🇰🇬" },
  { code: "LA", nameEn: "Laos", nameAr: "لاوس", flag: "🇱🇦" },
  { code: "LV", nameEn: "Latvia", nameAr: "لاتفيا", flag: "🇱🇻" },
  { code: "LB", nameEn: "Lebanon", nameAr: "لبنان", flag: "🇱🇧" },
  { code: "LS", nameEn: "Lesotho", nameAr: "ليسوتو", flag: "🇱🇸" },
  { code: "LR", nameEn: "Liberia", nameAr: "ليبيريا", flag: "🇱🇷" },
  { code: "LY", nameEn: "Libya", nameAr: "ليبيا", flag: "🇱🇾" },
  { code: "LI", nameEn: "Liechtenstein", nameAr: "ليختنشتاين", flag: "🇱🇮" },
  { code: "LT", nameEn: "Lithuania", nameAr: "ليتوانيا", flag: "🇱🇹" },
  { code: "LU", nameEn: "Luxembourg", nameAr: "لوكسمبورغ", flag: "🇱🇺" },
  { code: "MG", nameEn: "Madagascar", nameAr: "مدغشقر", flag: "🇲🇬" },
  { code: "MW", nameEn: "Malawi", nameAr: "ملاوي", flag: "🇲🇼" },
  { code: "MY", nameEn: "Malaysia", nameAr: "ماليزيا", flag: "🇲🇾" },
  { code: "MV", nameEn: "Maldives", nameAr: "المالديف", flag: "🇲🇻" },
  { code: "ML", nameEn: "Mali", nameAr: "مالي", flag: "🇲🇱" },
  { code: "MT", nameEn: "Malta", nameAr: "مالطا", flag: "🇲🇹" },
  { code: "MR", nameEn: "Mauritania", nameAr: "موريتانيا", flag: "🇲🇷" },
  { code: "MU", nameEn: "Mauritius", nameAr: "موريشيوس", flag: "🇲🇺" },
  { code: "MX", nameEn: "Mexico", nameAr: "المكسيك", flag: "🇲🇽" },
  { code: "MD", nameEn: "Moldova", nameAr: "مولدوفا", flag: "🇲🇩" },
  { code: "MC", nameEn: "Monaco", nameAr: "موناكو", flag: "🇲🇨" },
  { code: "MN", nameEn: "Mongolia", nameAr: "منغوليا", flag: "🇲🇳" },
  { code: "ME", nameEn: "Montenegro", nameAr: "الجبل الأسود", flag: "🇲🇪" },
  { code: "MA", nameEn: "Morocco", nameAr: "المغرب", flag: "🇲🇦" },
  { code: "MZ", nameEn: "Mozambique", nameAr: "موزمبيق", flag: "🇲🇿" },
  { code: "MM", nameEn: "Myanmar", nameAr: "ميانمار", flag: "🇲🇲" },
  { code: "NA", nameEn: "Namibia", nameAr: "ناميبيا", flag: "🇳🇦" },
  { code: "NP", nameEn: "Nepal", nameAr: "نيبال", flag: "🇳🇵" },
  { code: "NL", nameEn: "Netherlands", nameAr: "هولندا", flag: "🇳🇱" },
  { code: "NZ", nameEn: "New Zealand", nameAr: "نيوزيلندا", flag: "🇳🇿" },
  { code: "NI", nameEn: "Nicaragua", nameAr: "نيكاراغوا", flag: "🇳🇮" },
  { code: "NE", nameEn: "Niger", nameAr: "النيجر", flag: "🇳🇪" },
  { code: "NG", nameEn: "Nigeria", nameAr: "نيجيريا", flag: "🇳🇬" },
  { code: "KP", nameEn: "North Korea", nameAr: "كوريا الشمالية", flag: "🇰🇵" },
  { code: "MK", nameEn: "North Macedonia", nameAr: "مقدونيا الشمالية", flag: "🇲🇰" },
  { code: "NO", nameEn: "Norway", nameAr: "النرويج", flag: "🇳🇴" },
  { code: "OM", nameEn: "Oman", nameAr: "عمان", flag: "🇴🇲" },
  { code: "PK", nameEn: "Pakistan", nameAr: "باكستان", flag: "🇵🇰" },
  { code: "PS", nameEn: "Palestine", nameAr: "فلسطين", flag: "🇵🇸" },
  { code: "PA", nameEn: "Panama", nameAr: "بنما", flag: "🇵🇦" },
  { code: "PG", nameEn: "Papua New Guinea", nameAr: "بابوا غينيا الجديدة", flag: "🇵🇬" },
  { code: "PY", nameEn: "Paraguay", nameAr: "باراغواي", flag: "🇵🇾" },
  { code: "PE", nameEn: "Peru", nameAr: "بيرو", flag: "🇵🇪" },
  { code: "PH", nameEn: "Philippines", nameAr: "الفلبين", flag: "🇵🇭" },
  { code: "PL", nameEn: "Poland", nameAr: "بولندا", flag: "🇵🇱" },
  { code: "PT", nameEn: "Portugal", nameAr: "البرتغال", flag: "🇵🇹" },
  { code: "QA", nameEn: "Qatar", nameAr: "قطر", flag: "🇶🇦" },
  { code: "RO", nameEn: "Romania", nameAr: "رومانيا", flag: "🇷🇴" },
  { code: "RU", nameEn: "Russia", nameAr: "روسيا", flag: "🇷🇺" },
  { code: "RW", nameEn: "Rwanda", nameAr: "رواندا", flag: "🇷🇼" },
  { code: "SA", nameEn: "Saudi Arabia", nameAr: "السعودية", flag: "🇸🇦" },
  { code: "SN", nameEn: "Senegal", nameAr: "السنغال", flag: "🇸🇳" },
  { code: "RS", nameEn: "Serbia", nameAr: "صربيا", flag: "🇷🇸" },
  { code: "SC", nameEn: "Seychelles", nameAr: "سيشل", flag: "🇸🇨" },
  { code: "SL", nameEn: "Sierra Leone", nameAr: "سيراليون", flag: "🇸🇱" },
  { code: "SG", nameEn: "Singapore", nameAr: "سنغافورة", flag: "🇸🇬" },
  { code: "SK", nameEn: "Slovakia", nameAr: "سلوفاكيا", flag: "🇸🇰" },
  { code: "SI", nameEn: "Slovenia", nameAr: "سلوفينيا", flag: "🇸🇮" },
  { code: "SO", nameEn: "Somalia", nameAr: "الصومال", flag: "🇸🇴" },
  { code: "ZA", nameEn: "South Africa", nameAr: "جنوب أفريقيا", flag: "🇿🇦" },
  { code: "KR", nameEn: "South Korea", nameAr: "كوريا الجنوبية", flag: "🇰🇷" },
  { code: "SS", nameEn: "South Sudan", nameAr: "جنوب السودان", flag: "🇸🇸" },
  { code: "ES", nameEn: "Spain", nameAr: "إسبانيا", flag: "🇪🇸" },
  { code: "LK", nameEn: "Sri Lanka", nameAr: "سريلانكا", flag: "🇱🇰" },
  { code: "SD", nameEn: "Sudan", nameAr: "السودان", flag: "🇸🇩" },
  { code: "SR", nameEn: "Suriname", nameAr: "سورينام", flag: "🇸🇷" },
  { code: "SE", nameEn: "Sweden", nameAr: "السويد", flag: "🇸🇪" },
  { code: "CH", nameEn: "Switzerland", nameAr: "سويسرا", flag: "🇨🇭" },
  { code: "SY", nameEn: "Syria", nameAr: "سوريا", flag: "🇸🇾" },
  { code: "TW", nameEn: "Taiwan", nameAr: "تايوان", flag: "🇹🇼" },
  { code: "TJ", nameEn: "Tajikistan", nameAr: "طاجيكستان", flag: "🇹🇯" },
  { code: "TZ", nameEn: "Tanzania", nameAr: "تنزانيا", flag: "🇹🇿" },
  { code: "TH", nameEn: "Thailand", nameAr: "تايلاند", flag: "🇹🇭" },
  { code: "TG", nameEn: "Togo", nameAr: "توغو", flag: "🇹🇬" },
  { code: "TT", nameEn: "Trinidad and Tobago", nameAr: "ترينيداد وتوباغو", flag: "🇹🇹" },
  { code: "TN", nameEn: "Tunisia", nameAr: "تونس", flag: "🇹🇳" },
  { code: "TR", nameEn: "Turkey", nameAr: "تركيا", flag: "🇹🇷" },
  { code: "TM", nameEn: "Turkmenistan", nameAr: "تركمانستان", flag: "🇹🇲" },
  { code: "UG", nameEn: "Uganda", nameAr: "أوغندا", flag: "🇺🇬" },
  { code: "UA", nameEn: "Ukraine", nameAr: "أوكرانيا", flag: "🇺🇦" },
  { code: "AE", nameEn: "United Arab Emirates", nameAr: "الإمارات", flag: "🇦🇪" },
  { code: "GB", nameEn: "United Kingdom", nameAr: "المملكة المتحدة", flag: "🇬🇧" },
  { code: "US", nameEn: "United States", nameAr: "الولايات المتحدة", flag: "🇺🇸" },
  { code: "UY", nameEn: "Uruguay", nameAr: "أوروغواي", flag: "🇺🇾" },
  { code: "UZ", nameEn: "Uzbekistan", nameAr: "أوزبكستان", flag: "🇺🇿" },
  { code: "VE", nameEn: "Venezuela", nameAr: "فنزويلا", flag: "🇻🇪" },
  { code: "VN", nameEn: "Vietnam", nameAr: "فيتنام", flag: "🇻🇳" },
  { code: "YE", nameEn: "Yemen", nameAr: "اليمن", flag: "🇾🇪" },
  { code: "ZM", nameEn: "Zambia", nameAr: "زامبيا", flag: "🇿🇲" },
  { code: "ZW", nameEn: "Zimbabwe", nameAr: "زيمبابوي", flag: "🇿🇼" },
];

/**
 * Get country by code
 */
export function getCountryByCode(code: string): Country | undefined {
  return countries.find((c) => c.code === code);
}

/**
 * Search countries by name (English or Arabic)
 */
export function searchCountries(query: string, language: "en" | "ar" = "en"): Country[] {
  const lowerQuery = query.toLowerCase();
  return countries.filter((country) => {
    const name = language === "en" ? country.nameEn : country.nameAr;
    return name.toLowerCase().includes(lowerQuery);
  });
}
